import hashlib
import time
from typing import Any, Dict, Optional

class AliExpressAuth:
    """
    Generates IOP request signatures using the V1 MD5 algorithm.
    """

    def __init__(self, app_key: str, app_secret: str):
        self.app_key = app_key
        self.app_secret = app_secret

    @staticmethod
    def timestamp_ms() -> str:
        """Returns the current time in milliseconds."""
        return str(int(time.time() * 1000))
        
    def build_system_params(self, api_method: str, session: Optional[str] = None) -> Dict[str, str]:
        """
        Builds the system parameters required by the AliExpress API sync endpoint.
        """
        params = {
            "format": "json",
            "app_key": self.app_key,
            "sign_method": "md5",
            "v": "2.0",
            "timestamp": self.timestamp_ms(),
            "partner_id": "aliexpress-async-api",
            "method": api_method,
        }
        if session:
            params["session"] = session
        return params

    @staticmethod
    def _mix_str(value: Any) -> str:
        """Converts any value to string for signing."""
        if isinstance(value, str):
            return value
        elif isinstance(value, bytes):
            return value.decode("utf-8")
        else:
            return str(value)

    def sign(self, sys_params: Dict[str, str], business_params: Dict[str, str]) -> str:
        """
        Calculates the MD5 signature for the request.
        
        The signature is generated by:
        1. Joining all system and business parameters.
        2. Sorting them alphabetically by key.
        3. Concatenating: SECRET + key1value1key2value2... + SECRET.
        4. Calculating the MD5 hash and converting to uppercase.
        """
        # Combine all params
        sign_params = sys_params.copy()
        sign_params.update(business_params)
        
        # Sort keys
        keys = list(sign_params.keys())
        keys.sort()
        
        # Build concatenation string
        sign_str = self.app_secret + "".join(f"{k}{self._mix_str(sign_params[k])}" for k in keys) + self.app_secret
        
        return hashlib.md5(sign_str.encode("utf-8")).hexdigest().upper()
